# Generated by Django 4.1.1 on 2022-09-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None)),
                ('photo', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rols', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(default=None, max_length=20)),
                ('password', models.CharField(default=None, max_length=100)),
                ('rol_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.rols')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
                ('comment', models.TextField(default=None)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
    ]
