# Generated by Django 4.1.1 on 2022-09-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rols',
            old_name='rols',
            new_name='rol',
        ),
    ]
