# Generated by Django 4.1.1 on 2022-10-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_rols_rols_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
