# Generated by Django 4.1.1 on 2022-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rol_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
